services:
  secretdrop_backend:
    image: ghcr.io/bilustek/secretdrop/secretdrop-backend:latest
    environment:
      RESEND_API_KEY: "${RESEND_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      FROM_EMAIL: "${FROM_EMAIL}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      STRIPE_PRICE_ID: "${STRIPE_PRICE_ID}"
      SLACK_WEBHOOK_SUBSCRIPTIONS: "${SLACK_WEBHOOK_SUBSCRIPTIONS}"
      SLACK_WEBHOOK_NOTIFICATIONS: "${SLACK_WEBHOOK_NOTIFICATIONS}"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      SENTRY_DSN: "${SENTRY_DSN}"
      API_BASE_URL: "${API_BASE_URL}"
      FRONTEND_BASE_URL: "${FRONTEND_BASE_URL}"
      APPLE_CLIENT_ID: "${APPLE_CLIENT_ID}"
      APPLE_TEAM_ID: "${APPLE_TEAM_ID}"
      APPLE_KEY_ID: "${APPLE_KEY_ID}"
      APPLE_PRIVATE_KEY: "${APPLE_PRIVATE_KEY}"
      STRIPE_PROJECT_METAKEY: "${STRIPE_PROJECT_METAKEY}"
      STRIPE_PROJECT_METADATA: "${STRIPE_PROJECT_METADATA}"
      DEPLOY_NODE_HOSTNAME: "${DEPLOY_NODE_HOSTNAME}"

    volumes:
      - secretdrop_data:/app/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${DEPLOY_NODE_HOSTNAME}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://127.0.0.1:8080/healthz"]
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.secretdrop-backend.rule=Host(`api.secretdrop.us`)"
      - "traefik.http.routers.secretdrop-backend.entrypoints=websecure"
      - "traefik.http.routers.secretdrop-backend.tls=true"
      - "traefik.http.routers.secretdrop-backend.tls.certresolver=infracert"
      - "traefik.http.middlewares.secretdrop-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.secretdrop-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.secretdrop-ratelimit.ratelimit.period=1m"
      - "traefik.http.routers.secretdrop-backend.middlewares=secretdrop-ratelimit"
      - "traefik.http.services.secretdrop-backend.loadbalancer.server.port=8080"

      # ip allow
      - "traefik.http.middlewares.secretdrop-admin-ipallowlist.ipallowlist.sourcerange=${ADMIN_ALLOWED_IPS}"
      - "traefik.http.routers.secretdrop-backend-admin.rule=Host(`api.secretdrop.us`) && PathPrefix(`/api/v1/admin`)"
      - "traefik.http.routers.secretdrop-backend-admin.entrypoints=websecure"
      - "traefik.http.routers.secretdrop-backend-admin.tls=true"
      - "traefik.http.routers.secretdrop-backend-admin.tls.certresolver=infracert"
      - "traefik.http.routers.secretdrop-backend-admin.middlewares=secretdrop-admin-ipallowlist,secretdrop-ratelimit"
      - "traefik.http.routers.secretdrop-backend-admin.service=secretdrop-backend"

  secretdrop_frontend:
    image: ghcr.io/bilustek/secretdrop/secretdrop-frontend:latest
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.secretdrop-frontend.rule=Host(`secretdrop.us`)"
      - "traefik.http.routers.secretdrop-frontend.entrypoints=websecure"
      - "traefik.http.routers.secretdrop-frontend.tls=true"
      - "traefik.http.routers.secretdrop-frontend.tls.certresolver=infracert"
      - "traefik.http.services.secretdrop-frontend.loadbalancer.server.port=80"
      
      # ip allow
      - "traefik.http.routers.secretdrop-frontend-admin.rule=Host(`secretdrop.us`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.secretdrop-frontend-admin.entrypoints=websecure"
      - "traefik.http.routers.secretdrop-frontend-admin.tls=true"
      - "traefik.http.routers.secretdrop-frontend-admin.tls.certresolver=infracert"
      - "traefik.http.routers.secretdrop-frontend-admin.middlewares=secretdrop-admin-ipallowlist"
      - "traefik.http.routers.secretdrop-frontend-admin.service=secretdrop-frontend"

volumes:
  secretdrop_data: null

networks:
  traefik_net:
    external: true
